version: "3.9"

services:
  backend:
      build:
        context: ./backend
        args:
          - mode=prod
      command: sh -c "npx mikro-orm schema:create -r && npx mikro-orm migration:up && npm run prod"

  frontend:
      build:
        context: ./frontend
        args:
          - REACT_APP_API_BASE_URL=http://$MACHINE_HOST:8000/api/
          - mode=prod

  # # nginx
  nginx:
    image: nginx:latest
    ports:
      - 80:8080
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - frontend_build:/var/www/react
    depends_on:
      - backend
      - frontend
volumes:
  frontend_build: