version: "3.9"

services:
  postgres:
    image: postgres:14.5
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d postgres"]
      interval: 5s
      timeout: 5s
      retries: 50

  backend:
      build:
        context: ./backend
      ports:
        - 8000:8000
      command: sh -c "npx mikro-orm schema:update -r && npx mikro-orm migration:up && npx tsc && node dist/index.js"

  frontend:
      build:
        context: ./frontend
        dockerfile: Dockerfile.prod
        
  nginx:
    build:
      context: ./nginx
    ports:
      - 80:8080
    depends_on:
      - backend
      - frontend