version: "3.9"

services:
  # postgres
  postgres:
    image: postgres:14.5
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d postgres"]
      interval: 5s
      timeout: 5s
      retries: 50

  # backend
  backend:
    restart: on-failure:5
    build:
      context: ./backend
    command: bash -c "python manage.py makemigrations && python manage.py migrate && gunicorn backend.wsgi --bind 0.0.0.0:8000"
    volumes:
      - ./backend:/code
      - ./backend/tmp/mysqld:/run/mysqld
    ports:
      - "8000:8000"
    environment:
      - POSTGRES_NAME=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    depends_on:
      postgres:
        condition: service_healthy
      mongo:
        condition: service_started
      
  # frontend
  frontend:
    build:
      context: ./frontend
    volumes:
      - frontend_build:/frontend/build
    ports:
      - '3000:3000'
    stdin_open: true
    tty: true
    depends_on:
      - backend
      
  # nginx
  nginx:
    image: nginx:latest
    ports:
      - 80:8080
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - frontend_build:/var/www/react
    depends_on:
      - backend
      - frontend
volumes:
  frontend_build: