version: "3.9"

services:
  # postgres
  postgres:
    image: postgres:14.5
    volumes:
      - ./data/db:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d postgres"]
      interval: 5s
      timeout: 5s
      retries: 50

  # # backend
  # backend:
  #   restart: on-failure:5
  #   build:
  #     context: ./backend
  #   ports:
  #     - "8000:8000"
      
  # # frontend
  # frontend:
  #   build:
  #     context: ./frontend
  #   # volumes:
  #   #   - frontend_build:/frontend/build
  #   ports:
  #     - '3000:3000'
  #   stdin_open: true
  #   tty: true
  #   depends_on:
  #     - backend
      
  # # nginx
  # nginx:
  #   image: nginx:latest
  #   ports:
  #     - 80:8080
  #   volumes:
  #     - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
  #     - frontend_build:/var/www/react
  #   depends_on:
  #     - backend
  #     - frontend
# volumes:
#   frontend_build: