version: "3.9"

services:
  # postgres
  postgres:
    image: postgres:14.5
    # volumes:
    #   - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      - POSTGRES_HOST=localhost
      - POSTGRES_PORT=5432
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d postgres"]
      interval: 5s
      timeout: 5s
      retries: 50

  # # backend
  # backend:
  #   restart: on-failure:5
  #   build:
  #     context: .
  #   command: npm run dev
  #   ports:
  #     - "8000:8000"
  #   depends_on:
  #     - postgres